# First, build the base image (see Dockerfile) if necessary
# - if that is not built locally, the remote image will be pulled.
# Then, build with:
#	docker build -t ghcr.io/utkarshdalal/package-builder-gamenative-cgct --file Dockerfile.cgct .
# Push to GitHub registry with:
#	docker push ghcr.io/utkarshdalal/package-builder-gamenative-cgct
# This is done after changing this file or any of the
# scripts/setup-{ubuntu,android-sdk,cgct}.sh setup scripts.
# FROM ghcr.io/utkarshdalal/package-builder-gamenative
FROM ghcr.io/utkarshdalal/package-builder-gamenative

USER root
RUN sed -i 's|/data/data/com.termux|/data/data/app.gamenative|g' \
        /tmp/termux-packages/scripts/properties.sh && \
    sed -i 's|"com.termux"|"app.gamenative"|g' \
        /tmp/termux-packages/scripts/properties.sh
RUN mv /data/data/com.termux /data/data/app.gamenative

# Use root to replace the setup-cgct script with our local version run from within scripts/
COPY setup-cgct.sh /tmp/termux-packages/scripts/setup-cgct.sh
RUN chown builder:builder /tmp/termux-packages/scripts/setup-cgct.sh && chmod +x /tmp/termux-packages/scripts/setup-cgct.sh

USER builder

# Now run the setup script
RUN TERMUX_PKGS__BUILD__IS_DOCKER_BUILD='true' /tmp/termux-packages/scripts/setup-cgct.sh
