name: Docker Publish CGCT

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push CGCT Docker image
        uses: docker/build-push-action@v4
        with:
          context: scripts
          file: scripts/Dockerfile.cgct
          platforms: linux/amd64
          push: true
          tags: ghcr.io/utkarshdalal/gamenative-package-builder-cgct:latest
